### ISSUE TITLE
[Bug] v-world-map is not working as expected 

### ISSUE THREAD

**Issue by Jojoooo1** [creativetimofficial/ct-vuetify-material-dashboard-pro#7] opened 2019-09-11 17:26 UTC
### Version
1.0.3
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/
### Operating System
Ubuntu 18.04
### Device
Dell XPS 15
### Browser & Version
Mozilla
### Steps to reproduce
Go to Vuetify demo page
### What is expected?
1. Map should be contained within the Global Sales by Top Locations DIV

2. Country should be showed when hovering the map
### What is actually happening?
1. Part of the map is outside of the DIV

2. Country are not shown when hovering

---

**Comment by johnleider** [comment] 2019-09-23 13:53
What browser and version? Can you provide a screenshot of it overflowing? Thank you

**Comment by Jojoooo1** [comment] 2019-09-23 17:25
![Capture du 2019-09-23 14-24-32](https://user-images.githubusercontent.com/17641873/65447913-fce02580-de0d-11e9-9d83-71873a823bf7.png)

**Comment by Jojoooo1** [comment] 2019-09-23 17:28
It actually happen when internet connection is slow or broken

![Capture du 2019-09-23 14-24-32](https://user-images.githubusercontent.com/17641873/65448036-429cee00-de0e-11e9-89ab-fa20b8531ce1.png)

**Comment by johnleider** [comment] 2019-10-17 17:25
I need a reliable way to reproduce this, or a set or steps. I have been unable to recreate this.

**Comment by johnleider** [comment] 2020-04-24 19:18
Closing due to missing information.

**Closed as completed by johnleider** 2020-04-24 19:18 UTC
Labels: needs more information
