### ISSUE TITLE
[Feature Request] vee-validate dependencie is outoffdate

### ISSUE THREAD

**Issue by jcarlos66** [creativetimofficial/ct-vuetify-material-dashboard-pro#26] opened 2019-12-13 15:19 UTC
### What is your enhancement?
please update the vee-validate dependencie to version 3 in  Vuetify Material Dashboard PRO  vee-validate is not the current version 3, is the version 2
thanks

**Comment by johnleider** [comment] 2020-01-28 07:43
Duplicate of #25

**Closed as completed by johnleider** 2020-01-28 07:43 UTC
Labels: duplicate
